### ISSUE TITLE
Download of Mac x64 build fails

### ISSUE THREAD

**Issue by thebiblelover7** [ChurchApps/FreeShowWeb#10]
When attempting to download the x64 version of the mac app on the main page, it does not download. The arm64 version downloads properly though.

Upon looking at the code, it seems that the website is looking for a release with `FreeShow-1.2.1-x64-mac.zip` when the Github release has `FreeShow-1.2.1-mac.zip`.

<img width="964" alt="Screenshot 2024-07-31 at 10 24 57 AM" src="https://github.com/user-attachments/assets/ae80e008-57bf-4413-bb1a-b4855e2ceffe">

**Comment by thebiblelover7** [comment]
I think we should double check before the next release is published if the other platforms download will work. After ChurchApps/FreeShow@bccb8df was merged the Windows and Linux release names will change to a unified format.

Maybe the following lines have to be changed
https://github.com/ChurchApps/FreeShowWeb/blob/45842e137178f4f63116b664620ec8c2b8cf9478/src/lib/components/scripts/releases.ts#L64-L69

**Comment by vassbo** [comment]
Yep, I will do that.
